#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec 12 09:28:43 2018

@author: Maxwell
"""

annual_salary=float(input("Enter your annual salary:"))
portion_saved=float(input("Enter the percent of your salary to save, as a decimal:"))
i_i=float(input("Enter your dream house's price:"))
rais=float(input("Enter your percentage raise as a decimal:"))
current_savings=float(0)
months=float(0)
downpayment=0.25*i_i
r=float(0.04)
while downpayment>current_savings:
    current_savings=current_savings+0.04*current_savings*0.08333333333+annual_salary*0.0833333333333*portion_saved
    months=months+1
    if months%6==0:
        annual_salary=annual_salary+annual_salary*rais
print("number of months:",months)